### ISSUE TITLE
مشکل با انگولار 12

### ISSUE THREAD

**Issue by taher-changizi** [peymanebrahimi/MaterialJalaliMomentAdapter#7]
salam vaght bekheyr tebghe document neveshtid ke faghat MaterialJalaliMomentAdapterModule tuye app.module import beshe ba anjam in kar datepicker farsi nashod tebghe usage be multicalendar.module  JalaliMomentDateModule, ro ezafe kardid ke man ham ezafe kardam bazam farsi nashod aya baraye demo az hamin estefade shode?

**Comment by peymanebrahimi** [comment]
salam
bale, baraye demo az hamin estefadeh shodeh.
ghaedatan bayad kaar koneh.
age hanuz een moshkel ro darid, shayad ba eshterak project betunam komak konam

**Comment by taher-changizi** [comment]
salam vaght bekheyr
vaghti ke moment-jalali nasb bashe ezafe bar jalali-moment in ettefagh miofte

core.js:6456 ERROR TypeError: Cannot read properties of undefined (reading 'jMonth')
    at Locale.jMonths (index.js:215:1)
    at JalaliMomentDateAdapter.setLocale (material-jalali-moment-adapter.js:27:1)
    at new JalaliMomentDateAdapter (material-jalali-moment-adapter.js:19:1)
    at Object.factory (core.js:11512:1)
    at R3Injector.hydrate (core.js:11416:1)
    at R3Injector.get (core.js:11236:1)
    at NgModuleRef$1.get (core.js:25341:1)
    at Object.get (core.js:25055:1)
    at lookupTokenUsingModuleInjector (core.js:3342:1)
    at getOrCreateInjectable (core.js:3454:1)

**Comment by peymanebrahimi** [comment]
salam
age manzuretun een https://github.com/fingerpich/jalali-moment hastesh, projeye ma be oon dependency dare va lazem nist joda nasbesh konid.

**Comment by taher-changizi** [comment]
kheyr manzuram https://github.com/jalaali/moment-jalaali va https://github.com/fingerpich/jalali-moment hamzaman ruye yek projas ke projaro refactor kardam moment-jalali ro hazf kardam ok shode,merc
